# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: HAT Box
email: juliette dot regimbal at mail dot mcgill dot ca
description: >- # this means to ignore newlines until "baseurl:"
  Haptic Authoring Tool (HAT) Box is an extensible collection of haptic authoring tools. HAT Box is meant to help hapticians find a tool that meets their criteria, learn more about a particular one, or plan their own tool.
baseurl: "/~juliette/authoring" # the subpath of your site, e.g. /blog
url: "http://cim.mcgill.ca" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
#remote_theme: pmarsceill/just-the-docs
theme: just-the-docs

collections:
  posts:
    output: true
  docs:
    output: true
  tools:
    permalink: "/:collection/:title/"
    output: true

just_the_docs:
  collections:
    docs:
      name: Documentation
      search_exclude: true
    tools:
      name: Tools
      search_exclude: false

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/JRegimbal/authoring-tool-website"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE.txt
